spring.application.name=profileDemo


app.welcome.message = LOCAL : Hello, Welcome to my Application !
app.welcome.code = 200
app.welcome.users = Rohit, Aditya, Mohan, Sohan

spring.profiles.active = dev